micronaut:
  application:
    name: mongoJsonViewBug
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://surmai_auth:hunter2@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/surmai_auth

---
jackson:
  serializationInclusion: ALWAYS
  json-view:
    enabled: true
  mapper:
    default-view-inclusion: false